services:
  - type: web
    name: superbrain-backend
    env: python
    plan: free
    region: frankfurt  # or oregon etc
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
